language: java

matrix:
   include:
      - os: linux
        dist: xenial
        jdk: openjdk11
        env: ADDITIONAL_MAVEN_ARGS="-Montana coveralls:report"
      - os: linux
        dist: xenial
        jdk: openjdk8
        if: type IN (pull_request)
      - os: osx
        osx_image: xcode10.1
        if: type IN (pull_request) OR commit_message =~ /^Merge pull request/

install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f com.examples.myproject/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS